// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7EB0-UDn1W4MZdbQm_B-FPXzwZ105g-M',
    appId: '1:858492692446:web:e93d1308ec7b6885c79f4f',
    messagingSenderId: '858492692446',
    projectId: 'cold-storage-inventory',
    authDomain: 'cold-storage-inventory.firebaseapp.com',
    storageBucket: 'cold-storage-inventory.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa38U_jCqFFsj1_OVb33xPhZj3oI04sxs',
    appId: '1:858492692446:android:3999f10066614fbec79f4f',
    messagingSenderId: '858492692446',
    projectId: 'cold-storage-inventory',
    storageBucket: 'cold-storage-inventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI7JZZSHgBeHPnRgumZUzaP7XDLfVmY14',
    appId: '1:858492692446:ios:004a275be29ac93dc79f4f',
    messagingSenderId: '858492692446',
    projectId: 'cold-storage-inventory',
    storageBucket: 'cold-storage-inventory.firebasestorage.app',
    iosBundleId: 'com.example.businessManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI7JZZSHgBeHPnRgumZUzaP7XDLfVmY14',
    appId: '1:858492692446:ios:004a275be29ac93dc79f4f',
    messagingSenderId: '858492692446',
    projectId: 'cold-storage-inventory',
    storageBucket: 'cold-storage-inventory.firebasestorage.app',
    iosBundleId: 'com.example.businessManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7EB0-UDn1W4MZdbQm_B-FPXzwZ105g-M',
    appId: '1:858492692446:web:f7f8f1541ddce1fac79f4f',
    messagingSenderId: '858492692446',
    projectId: 'cold-storage-inventory',
    authDomain: 'cold-storage-inventory.firebaseapp.com',
    storageBucket: 'cold-storage-inventory.firebasestorage.app',
  );

}